### ISSUE TITLE
 failed to install hdf5r 

### ISSUE THREAD

**Issue by Sophia409** [mojaveazure/loomR#30] opened 2019-02-17 08:10 UTC
I failed to install hdf5r using this command provided by https://satijalab.org/seurat/mca_loom.html: devtools::install_github(repo = 'hhoeflin/hdf5r'),below is the code,can you help me ?
![image](https://user-images.githubusercontent.com/30619010/52910146-2c560f00-32ce-11e9-9195-f4748f9f06cb.png)

![image](https://user-images.githubusercontent.com/30619010/52910141-22341080-32ce-11e9-910f-c9b5c8b1a1be.png)

![image](https://user-images.githubusercontent.com/30619010/52910131-07fa3280-32ce-11e9-8a6b-59823801c23f.png)

**Comment by mschilli87** [comment] 2019-02-17 08:19
duplicate of https://github.com/mojaveazure/loomR/issues/29?

**Closed as completed** 2019-02-24 07:22 UTC
